spring:
  #  redis:
  #    host: redis-1.shit-code.com
  #    port: 6379
  redis:
    cluster:
      nodes:
        - redis-1.shit-code.com:6379
        - redis-2.shit-code.com:6379
        - redis-3.shit-code.com:6379
        - redis-4.shit-code.com:6379
        - redis-5.shit-code.com:6379
        - redis-6.shit-code.com:6379