shit:
  spring:
    datasource:
      url: jdbc:mysql://172.28.0.21:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    boot:
      admin:
        client:
          url: http://172.28.0.101:8080

spring:
  redis:
    host: 172.28.0.31
    port: 6379

