spring:
  redis: ${shit.spring.redis}

---
spring:
  profiles: dev
shit:
  spring:
    redis:
      host: 172.28.0.31
---
spring:
  profiles: cluster
shit:
  spring:
    redis:
      cluster:
        nodes:
          - redis-1.shit-code.com:6379
          - redis-2.shit-code.com:6379
          - redis-3.shit-code.com:6379
          - redis-4.shit-code.com:6379
          - redis-5.shit-code.com:6379
          - redis-6.shit-code.com:6379