spring:
  boot:
    admin:
      client:
        url: ${shit.spring.boot.admin.client.url}
        auto-deregistration: true
        instance:
          prefer-ip: true
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
          management-base-url: http://${spring.cloud.client.ip-address}:${server.port}
---
spring:
  profiles: dev
shit:
  spring:
    boot:
      admin:
        client:
          url: http://172.28.0.101:8080
---
spring:
  profiles: cluster
shit:
  spring:
    boot:
      admin:
        client:
          url:
            - http://admin-1.shit-code.com:8080
            - http://admin-2.shit-code.com:8080
