spring:
  datasource:
    url: jdbc:mysql://mysql-master.shit-code.com:3306/?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  boot:
    admin:
      client:
        url:
          - http://admin-1.shit-code.com:8080
          - http://admin-2.shit-code.com:8080
  redis:
    cluster:
      nodes:
        - redis-1.shit-code.com:6379
        - redis-2.shit-code.com:6379
        - redis-3.shit-code.com:6379
        - redis-4.shit-code.com:6379
        - redis-5.shit-code.com:6379
        - redis-6.shit-code.com:6379