spring:
  boot:
    admin:
      client:
        url: ${shit.spring.boot.admin.client.url}
        auto-deregistration: true
        instance:
          prefer-ip: true
          service-base-url: http://${spring.cloud.client.ip-address}:${server.port}
          management-base-url: http://${spring.cloud.client.ip-address}:${server.port}
