spring:
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

server:
  undertow:
    threads:
      io: 16
      worker: 256
    direct-buffers: true
    accesslog:
      enabled: true
      rotate: true
      dir: ${logging.file.path}/undertow
      pattern: combined
#    buffer-size:

