spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true
logging:
  config: classpath:config/logback-spring.xml

management:
  endpoint:
    refresh:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'