spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
logging:
  config: classpath:config/logback-spring.xml

