spring:
  cloud:
    consul:
      discovery:
        tags: version=0.0.1,author=cd871127
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}
        query-passing: true
        prefer-ip-address: true
        health-check-critical-timeout: 10s
        health-check-timeout: 5s
        deregister: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    addresses: 172.28.0.41