spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: host_route
          uri: http://www.youdao.com
          predicates:
            - Path=/foo/**,/bar/{segment}
