spring:
  profiles:
#    include:
    active: admin
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://www.baidu.com/s/
          predicates:
            - Path=/*
          filters:
            - AddRequestParameter=wd, github
server:
  port: 8889

management:
  endpoints:
    web:
      exposure:
        include: health,status,gateway
